      double precision autoang
      integer maxatom,maxpair,maxdata,maxterm,maxperm
      parameter(autoang=0.529177249d0)
      parameter(maxatom=100)    ! max total atoms
      parameter(maxpair=50)    ! max atom-atoms pairs
      parameter(maxdata=200) ! max fitting data
      parameter(maxterm=5000) ! max number of polynomial terms
      parameter(maxperm=1000000)    ! max number of symmetry permutations

